name: PHP Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install PHPUnit
      run: composer require --dev phpunit/phpunit

    - name: Run Tests
      run: |
        vendor/bin/phpunit tests
